dataset = "Ciao"
upath_filename = "./data/" + dataset +"/" + "upath.txt"
ipath_filename = "./data/" + dataset +"/" + "ipath.txt"
train_filename = "./data/" + dataset +"/" + "ui_trainset37.txt"
test_filename = "./data/" + dataset +"/" + "ui_testset37.txt"
# train_filename = "./data/" + dataset +"/" + "ui_trainset28.txt"
# test_filename = "./data/" + dataset +"/" + "ui_testset28.txt"
# train_filename = "./data/" + dataset +"/" + "ui_trainset19.txt"
# test_filename = "./data/" + dataset +"/" + "ui_testset19.txt"
uu_filename = "./data/" + dataset +"/" + "trusts.txt"
embfile = "./results/" + dataset +"/" + "_dis_.emb"
result_file = "./results/" + dataset +"/" + "measure.txt"
threshhold = 3
maxM = 20
max_path_len = 4
emb_dim = 64
batch_size = 256
epochs = 100
lr_default = 0.001
lr_decay_rate = 0.5
seed = 6666
